repos:
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks: [ {id: black} ]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks: [ {id: mypy, args: [--strict]} ]

- repo: https://github.com/golangci/golangci-lint
  rev: v1.59.1
  hooks: [ {id: golangci-lint} ]
