version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"
  
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper