name: CI

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [python]

    steps:
    - uses: actions/checkout@v4

    # ---------- Python ----------
    - name: Set up Python
      if: matrix.lang == 'python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'                # built-in pip cache

    - name: Install deps
      if: matrix.lang == 'python'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Lint & Tests
      if: matrix.lang == 'python'
      run: |
        ruff .
        mypy src/
        pytest -q
    
    - name: Build wheel
      if: matrix.lang == 'python'
      run: python -m build --wheel
      # The command writes the wheel into ./dist/
      # Docs: https://pypa-build.readthedocs.io/en/stable/  :contentReference[oaicite:0]{index=0}

    # ---------- Build & push Docker images ----------
    #   unchanged; just make sure Dockerfile uses requirements.txt too
